force-app/main/default/objects/CM_Account_Team_History__c/CM_Account_Team_History__c.object-meta.xml
<CustomObject>
    <label>NA Sales Team History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA Sales Team History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CM_Account_Team_History__c/fields/Account_Firm__c.field-meta.xml
<CustomField>
    <fullName>Account_Firm__c</fullName>
    <label>Company/Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NA Sales Team History</relationshipLabel>
    <relationshipName>CM_Account_Team_Historys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CM_Account_Team_History__c/fields/SCE_Validated__c.field-meta.xml
<CustomField>
    <fullName>SCE_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCE Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CM_Account_Team_History__c/fields/Survey_Validated_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Survey_Validated_Date_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Validated Date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/Service_AMT__c.object-meta.xml
<CustomObject>
    <label>Service AMT</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service AMT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service AMT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_AMT__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service AMT</relationshipLabel>
    <relationshipName>Service_AMT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/SCE_Validated__c.field-meta.xml
<CustomField>
    <fullName>SCE_Validated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCE Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/Survey_Validated_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Survey_Validated_Date_time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Survey Validated Date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/User_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Contact_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User/ Contact Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClearCSSCEValidationBatchTest.cls
@isTest
public class ClearCSSCEValidationBatchTest {
    @testSetup
    static void setupTestData() {
        Account acc = new Account();
            acc.Name = 'Test Account Record';
            acc.Subtype__c ='National Accounts - East';
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Existing Client').getRecordTypeId();
            insert acc;
        
        List<Service_AMT__c> amtRecords = new List<Service_AMT__c>();

        for (Integer i = 0; i < 10; i++) {
            amtRecords.add(new Service_AMT__c(
                Name = 'Test AMT Record ' + i,
                Company__c = acc.Id, User_Contact_Id__c = '1',
                SCE_Validated__c = true,
                Survey_Validated_Date_time__c = DateTime.now().addDays(-i)
            ));
        }

        insert amtRecords;
        
        List<CM_Account_Team_History__c> NASaleRecords = new List<CM_Account_Team_History__c>();

        for (Integer i = 0; i < 10; i++) {
            NASaleRecords.add(new CM_Account_Team_History__c(
                Name = 'Test AMT Record ' + i,
                Account_Firm__c = acc.Id,
                SCE_Validated__c = true,
                Survey_Validated_Date_time__c = DateTime.now().addDays(-i)
            ));
        }

        insert NASaleRecords;
    }

    @isTest
    static void testBatchExecution() {
        Test.startTest();
        ClearCSSCEValidationBatch batch = new ClearCSSCEValidationBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();

    }
    
    @isTest
    static void testBatchExecutionNASales() {
        Test.startTest();
        ClearNASaleCSSCEValidationBatch batch = new ClearNASaleCSSCEValidationBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();

    }
}