force-app/main/default/objects/Policy_Information__c/Policy_Information__c.object-meta.xml
<CustomObject>
    <label>Policy Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Information__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Information</relationshipLabel>
    <relationshipName>Policy_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PolicyBatchProcessor.cls
global class PolicyBatchProcessor
implements Database.Batchable<SObject>, Database.AllowsCallouts {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Policy__c, Company__c
            FROM Policy_Information__c
        ]);
    }

    global void execute(Database.BatchableContext bc, List<Policy_Information__c> scope) {

        if (!scope.isEmpty()) {
            AccountAPI.sendBulkPolicies(scope);
        }
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('Batch Completed');
    }
}