force-app/main/default/objects/Policy_Information__c/Policy_Information__c.object-meta.xml
<CustomObject>
    <label>Policy Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Information__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Information</relationshipLabel>
    <relationshipName>Policy_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Policy_Status__c.field-meta.xml
<CustomField>
    <fullName>Policy_Status__c</fullName>
    <label>Policy Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policycase__c/Policycase__c.object-meta.xml
<CustomObject>
    <description>PolicyCaseAssociation</description>
    <label>Policy</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Policy Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policycase__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>PolicyCaseAssociation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policycase__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <label>Policy</label>
    <referenceTo>Policy_Information__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>PolicyCaseAssociation</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Service_AMT__c/Service_AMT__c.object-meta.xml
<CustomObject>
    <label>Service AMT</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Service AMT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service AMT</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_AMT__c/fields/All_Policy__c.field-meta.xml
<CustomField>
    <fullName>All_Policy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Policy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service AMT</relationshipLabel>
    <relationshipName>Service_AMT</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_AMT__c/fields/UserHierarchy__c.field-meta.xml
<CustomField>
    <fullName>UserHierarchy__c</fullName>
    <defaultValue>1</defaultValue>
    <label>User Hierarchy</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>Staff</label>
    <nameField>
        <displayFormat>CM-{0000}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/Staff_Name__c.field-meta.xml
<CustomField>
    <fullName>Staff_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staff Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Staffing_Model</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/Staff_Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object between Staff &amp; Policy Information</description>
    <label>Staff Assignment</label>
    <nameField>
        <displayFormat>SA-{0000}</displayFormat>
        <label>Staff Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Assignment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Assignment__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Competitor, Consulting Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Staff Assignment</relationshipLabel>
    <relationshipName>Staff_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/fields/Medical_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Medical_Policy_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy Number</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Active Policy which belongs to this Customer.</errorMessage>
        <filterItems>
            <field>$Source.Customer_Name__c</field>
            <operation>equals</operation>
            <valueField>Policy_Information__c.Company__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Policy_Information__c</referenceTo>
    <relationshipLabel>Staff Assignment</relationshipLabel>
    <relationshipName>Staff_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/fields/Role_on_Case__c.field-meta.xml
<CustomField>
    <fullName>Role_on_Case__c</fullName>
    <label>Role on Case</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Manager</fullName>
            </value>
            <value>
                <fullName>Benefit Consultant</fullName>
            </value>
            <value>
                <fullName>Client Management Consultant</fullName>
            </value>
            <value>
                <fullName>UMR Client Manager</fullName>
            </value>
            <value>
                <fullName>Implementation Project Manager</fullName>
            </value>
            <value>
                <fullName>Surest Client Manager</fullName>
            </value>
            <value>
                <fullName>Surest Implementation Project Manager</fullName>
            </value>
            <value>
                <fullName>Specialty Benefits Client Manager</fullName>
            </value>
            <value>
                <fullName>Specialty Benefits Consultant</fullName>
                <isActive>false</isActive>
                <label>Specialty Benefits Consultant</label>
            </value>
            <value>
                <fullName>Surest Account Associate</fullName>
                <isActive>false</isActive>
                <label>Surest Account Associate</label>
            </value>
            <value>
                <fullName>Surest Project Implementation Manager</fullName>
                <isActive>false</isActive>
                <label>Surest Project Implementation Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/fields/Should_Extended_AMT_be_updated__c.field-meta.xml
<CustomField>
    <fullName>Should_Extended_AMT_be_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Extended AMT be updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/fields/Staff_User_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Staff_User_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staff Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND (2 OR 3)) OR (4 AND (5 OR 6 OR 7)) OR (8 AND (9 OR 10))</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>IPM Assignment</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e3s000000VQPOAA4</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e3s000000VQPTAA4</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Policy Assignment</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e6A000001o32SQAQ</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e3s000000ieLEAAY</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e6A000001o32TQAQ</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Project</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e3s000000VQPOAA4</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Id</field>
            <operation>equals</operation>
            <value>00e3s000000VQPTAA4</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Staff_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff_Assignment__c/fields/Staffing_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Staffing_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Staff ID</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>IPM Assignment</value>
        </filterItems>
        <filterItems>
            <field>Staff__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>IPM Staff</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Policy Assignment</value>
        </filterItems>
        <filterItems>
            <field>Staff__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>CSI Staff</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Project</value>
        </filterItems>
        <filterItems>
            <field>Staff__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>IPM Staff</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>Staff Assignment</relationshipLabel>
    <relationshipName>Staffing_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/staffAssignmentTriggerHelperTest.cls
/**
* Purpose     : test class for staffAssignmentTriggerHelper and staffAssignmentTrigger
* =============================================================================
* History
* -----------------------
* VERSION     AUTHOR                     DATE            DETAIL
*   1.0      GHANSHYAM CHOUDHARI         Nov 2019     Initial Class
*==============================================================================
*/

@isTest
private class staffAssignmentTriggerHelperTest {
    //staff
    //customer
    //user
    @isTest
    static void setupTestData(){       
        try{
            
            Map<Id,Staff_Assignment__c> newMap = new Map<Id,Staff_Assignment__c>();
            Map<Id,Staff_Assignment__c> oldMap = new Map<Id,Staff_Assignment__c>();
            
            Date newDate = Date.today().addDays(-1);
            Map<id,Staff_Assignment__c> maplist = new Map<id,Staff_Assignment__c>();
            
            List<Account> accountList = new List<Account>();
            List<Case> caseList = new List<Case>();
            List<Policy_Information__c> policyInfnList = new List<Policy_Information__c>();
            
            Account acc= new account (); 
            acc.name='test account';
            acc.Subtype__c='Enterprise Strategic Accounts';
            accountList.add(acc);
            Account acc1= new account ();
            acc1.name='test account1';
            acc1.Subtype__c='Enterprise Strategic Accounts';
            accountList.add(acc1);
            insert accountList;
            case c = new case();
            c.accountId=accountList[0].Id;
            caseList.add(c);
            system.debug('variable@@@'+c.Priority);
            case c2 = new case();
            c2.accountId=accountList[0].Id;
            c2.Priority='Low';
            insert caseList;
            
            
            Policy_Information__c p = new Policy_Information__c();
            p.Name='77341234';
            p.Policy_Status__c = 'Active';
            p.Policy__c = '77341234';
            p.Company__c=accountList[0].Id;
            policyInfnList.add(p);
            
            Policy_Information__c p1 = new Policy_Information__c();
            p1.Name='79341234';
            p1.Policy__c = '79341234';
            p1.Company__c=accountList[0].Id;
            policyInfnList.add(p1);
            
            insert policyInfnList;
            
            Policycase__c pc = new Policycase__c();
            pc.Policy__c=policyInfnList[0].Id;
            pc.Case__c=caseList[0].Id;
            insert pc;
            
            Map<Id,Policy_Information__c> policyMap = new Map<Id,Policy_Information__c>();
            Profile pf= [Select Id from Profile where Name='System Administrator'];     
            String orgId=UserInfo.getOrganizationId(); 
            String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','') ;
            Integer RandomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
            String uniqueName=orgId+dateString+RandomId; 
            String uniqueName2=orgId+dateString+RandomId+'zz'; 
            
            User uu=new User(firstname = 'ABC', 
                             lastName = 'XYZ', 
                             email = uniqueName + '@crmit' + '.com', 
                             Username = uniqueName + '@test' + orgId + '.org', 
                             EmailEncodingKey = 'ISO-8859-1', 
                             Alias = uniqueName.substring(18, 23), 
                             TimeZoneSidKey = 'America/Los_Angeles', 
                             LocaleSidKey = 'en_US', 
                             LanguageLocaleKey = 'en_US', 
                             ProfileId = pf.Id,
                             Position__c='Salesforce Courtesy License'
                            );  
            insert uu;       
            
            Staff__c s =new Staff__c();
            s.Staff_Name__c=uu.id; 
            insert s;
            
            
            list<Staff_Assignment__c> ls = new list<Staff_Assignment__c>();
            list<Staff_Assignment__c> ls1 = new list<Staff_Assignment__c>();
            
            Staff_Assignment__c sa = new Staff_Assignment__c();
            sa.Customer_Name__c= acc.id;
            sa.Staff_User_Assignment__c=uu.Id;
            sa.Staffing_Assignment__c=s.id;
            sa.Role_on_Case__c='Client Manager';    
            sa.Medical_Policy_Number__c =p.id;
            ls.add(sa);
            
            Staff_Assignment__c sa1 = new Staff_Assignment__c();
            sa1.Customer_Name__c= acc.id;
            sa1.Staffing_Assignment__c=s.id;
            sa1.Role_on_Case__c='Client Manager'; 
            ls.add(sa1);
            
            Staff_Assignment__c sa2 = new Staff_Assignment__c();
            sa2.Customer_Name__c= acc.id;
            sa2.Staff_User_Assignment__c=uu.Id;
            sa2.Role_on_Case__c='Client Manager';
            ls.add(sa2);
            
            
            Staff_Assignment__c sa3 = new Staff_Assignment__c();
            sa3.Customer_Name__c= acc.id;
            sa3.Role_on_Case__c='Client Manager'; 
            ls.add(sa3);  
            
            Service_AMT__c ser = new Service_AMT__c();
            ser.Company__c= acc.id;
            ser.First_Name__c ='test';
            ser.Last_Name__c = 'test';
            ser.Email__c = 'test@test.com';
            ser.All_Policy__c = true;
            ser.UserHierarchy__c = 1;
            insert ser;   

            Database.insert(ls,false);
            
            newMap.put(sa.id,sa);
            oldMap.put(sa1.id,sa1);
            staffAssignmentTriggerHelper.staffAssignmentUpdate(newMap,oldMap);
            staffAssignmentTriggerHelper.staffAssignmentUpdate(oldMap,newMap);
            
            newMap.clear();
            oldMap.clear();
            
        }
        catch(Exception e){
            //System.Assert(e.getMessage().contains('Please select matching staff or leave this field blank'));
            system.debug('Exception occured '+e);
        }
        
        /*list<Staff_Assignment__c> updateSA = new list<Staff_Assignment__c>();
list<Staff_Assignment__c> sUpdate1 = [select id from Staff_Assignment__c where Staffing_Assignment__c=:s.id];


for(Staff_Assignment__c eachSA : sUpdate1){
eachSA.Should_Extended_AMT_be_updated__c = true;
}

update sUpdate1;

System.assertequals('XYZ',uu.LastName,'user last name');
Integer num = [select count() from Policy_Information__c];
System.assertEquals(2, num,'total number of policy information created'); 
System.assertequals('Low',c2.Priority,'priority of case 2');
Integer num1 = [select count() from Staff_Assignment__c];
System.debug('Staff_Assignment__c count: '+num1); 
System.assertEquals(1, num1,'total number of staff assignment created');*/
        
    }
}