force-app/main/default/objects/Policy_Information__c/Policy_Information__c.object-meta.xml
<CustomObject>
    <label>Policy Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Information__c/fields/Add_ons_Sum_of_total_input__c.field-meta.xml
<CustomField>
    <fullName>Add_ons_Sum_of_total_input__c</fullName>
    <label>Add-ons (Sum of total input value)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Information</relationshipLabel>
    <relationshipName>Policy_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/CSP_GSP_or_Extended_Networks__c.field-meta.xml
<CustomField>
    <fullName>CSP_GSP_or_Extended_Networks__c</fullName>
    <inlineHelpText>Does customer have a CSP/GSP or Extended Network set-up?</inlineHelpText>
    <label>CSP/GSP or Extended Networks</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 that require ongoing activity after setup</fullName>
            </value>
            <value>
                <fullName>1 that require ongoing activity after setup</fullName>
            </value>
            <value>
                <fullName>2 or more that require ongoing activity after setup?</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <isActive>false</isActive>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Customer_Sponsored_Service_Center__c.field-meta.xml
<CustomField>
    <fullName>Customer_Sponsored_Service_Center__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>A customer-sponsored service center is defined as a group the CM interacts with on a regular basis (i.e. minimum of monthly contact)</inlineHelpText>
    <label>Customer - Sponsored Service Center</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/DHP_Diabetes_Health_Plan__c.field-meta.xml
<CustomField>
    <fullName>DHP_Diabetes_Health_Plan__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Does your customer have a Diabetes Health Plan (DHP)?</inlineHelpText>
    <label>zzDHP (Diabetes Health Plan)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Eligibility__c</fullName>
    <defaultValue>&quot;0-Vendor Generated&quot;</defaultValue>
    <inlineHelpText>Please respond with how the majority of your population is handled.</inlineHelpText>
    <label>Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0-Vendor Generated</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1-Customer Generated, Manual file</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2-Manual Eligibility file</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/FSA_c__c.field-meta.xml
<CustomField>
    <fullName>FSA_c__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Does UHC handle the Financial Products? (FSA,RRA,HRA,CERA,HIA,HSA,etc.)?</inlineHelpText>
    <label>Financial Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Hospital_Systemss__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Systemss__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Is customer a hospital system or own one?</inlineHelpText>
    <label>Hospital Systems</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Life__c.field-meta.xml
<CustomField>
    <fullName>Life__c</fullName>
    <defaultValue>&quot;0&quot;</defaultValue>
    <inlineHelpText>Sold by UHC as Integrated or Stand-Alone</inlineHelpText>
    <label>Life</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Medicare_Plan__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Plan__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Include Medicare plans on the UNET platform.  (Do not include Retiree Solutions plans.  Do include Medicare Advantage mirror plans as well as any Medicare supplemental plans on the UNET platform)</inlineHelpText>
    <label>Medicare Plans</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/ne_Business_Exchange_Transition_Factor__c.field-meta.xml
<CustomField>
    <fullName>ne_Business_Exchange_Transition_Factor__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Include customers who are new to UHC as well as customers who are moving to/from private exchanges.  Credit should be valid for first year after implementation/effective date.</inlineHelpText>
    <label>New Business/Exchange Transition Factor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/New_Product_1st_Year_1__c.field-meta.xml
<CustomField>
    <fullName>New_Product_1st_Year_1__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>New Products refers to new product for UHG only.  Any or all of the following activities: New Products, pilots(internal or customer-specific), UHG Driven platform migration.  Do not count established products that are new to a customer.</inlineHelpText>
    <label>New Product 1st Year (1)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Policy Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Rental_Networks__c.field-meta.xml
<CustomField>
    <fullName>Rental_Networks__c</fullName>
    <inlineHelpText>UMR Customer using Non-UHC network (i.e. Rental Network).</inlineHelpText>
    <label>Rental Networks</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/Salesforce_Volume__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Number of issues on policy in rolling year excluding IS Requests, BCI Review, SBS Support.</inlineHelpText>
    <label>Merit Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/UHG_Owned_Custom_Portal__c.field-meta.xml
<CustomField>
    <fullName>UHG_Owned_Custom_Portal__c</fullName>
    <defaultValue>&quot;0 - No&quot;</defaultValue>
    <inlineHelpText>Does your customer have a UHG-owned custom portal?  (does not include custom myuhc or pre-member websites) ie Fertility benefit promotion</inlineHelpText>
    <label>UHG Owned Custom Portal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>0 - No</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 - Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Information__c/fields/UMR_SBC__c.field-meta.xml
<CustomField>
    <fullName>UMR_SBC__c</fullName>
    <inlineHelpText>Whether UMR creates the SBC on behalf of the customer.</inlineHelpText>
    <label>UMR SBC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DontAllowDuplicatePolicyNumbersTest.cls
/**
* Purpose     : Test class for DontAllowDuplicatePolicyNumbersTest
* =============================================================================
* History
* -----------------------
* VERSION     AUTHOR                     DATE            DETAIL
*   1.0      GHANSHYAM CHOUDHARI         Nov 2019     Initial Class
*==============================================================================
*/
@isTest
public class DontAllowDuplicatePolicyNumbersTest {
    
    @isTest
    static void dontAllowDuplicatePolicies(){
        
            Boolean expectedExceptionThrown;
            
            list<Policy_Information__c> listOfpolicies = new list<Policy_Information__c>();
            Map<Id,Policy_Information__c> newMap = new Map<Id,Policy_Information__c>();
            Map<Id,Policy_Information__c> oldMap = new Map<Id,Policy_Information__c>();
            
            Account acc = new Account(Name = 'Test CD Account', 
                                      Subtype__c ='Prospect',
                                      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId());
            insert acc;
            
            Policy_Information__c policy = new Policy_Information__c(Name = '720455', 
                                                                     Company__c = acc.Id, 
                                                                     Policy__c = 'Test',
                                                                     CSP_GSP_or_Extended_Networks__c = '0 that require ongoing activity after setup',
                                                                     Customer_Sponsored_Service_Center__c = '1',
                                                                     DHP_Diabetes_Health_Plan__c = '0',
                                                                     Eligibility__c = '0',
                                                                     FSA_c__c = '0',
                                                                     Hospital_Systemss__c = '0',
                                                                     Life__c	= '0',
                                                                     Medicare_Plan__c = '0',
                                                                     ne_Business_Exchange_Transition_Factor__c = '0',
                                                                     UHG_Owned_Custom_Portal__c = '0',
                                                                     New_Product_1st_Year_1__c = 1,
                                                                     UMR_SBC__c = 5,
                                                                     Rental_Networks__c = 'Yes');
            insert policy;
            
            
            policy.Eligibility__c = '1';
            
            update policy;
            
            
            Policy_Information__c updatedPolicyInfo = new Policy_Information__c(Id=policy.Id, Name = '00886737', 
                                                                                Company__c = acc.Id,Policy__c = 'Test', 
                                                                                CSP_GSP_or_Extended_Networks__c = '0 that require ongoing activity after setup',
                                                                                Customer_Sponsored_Service_Center__c = '1',
                                                                                DHP_Diabetes_Health_Plan__c = '0',
                                                                                Eligibility__c = '0',
                                                                                FSA_c__c = '0',
                                                                                Hospital_Systemss__c = '0',
                                                                                Life__c	= '0',
                                                                                Medicare_Plan__c = '0',
                                                                                ne_Business_Exchange_Transition_Factor__c = '0',
                                                                                UHG_Owned_Custom_Portal__c = '0',
                                                                                New_Product_1st_Year_1__c = 1,
                                                                                UMR_SBC__c = 5,
                                                                                Rental_Networks__c = 'Yes');
            update updatedPolicyInfo;
            
            
            
            Policy_Information__c policy1 = new Policy_Information__c(Name = '00886737', 
                                                                      Company__c = acc.Id,Policy__c = 'Test', 
                                                                      CSP_GSP_or_Extended_Networks__c = '0 that require ongoing activity after setup',
                                                                      Customer_Sponsored_Service_Center__c = '1',
                                                                      DHP_Diabetes_Health_Plan__c = '0',
                                                                      Eligibility__c = '0',
                                                                      FSA_c__c = '0',
                                                                      Hospital_Systemss__c = '0',
                                                                      Life__c	= '0',
                                                                      Medicare_Plan__c = '0',
                                                                      ne_Business_Exchange_Transition_Factor__c = '0',
                                                                      UHG_Owned_Custom_Portal__c = '0',
                                                                      New_Product_1st_Year_1__c = 1,
                                                                      UMR_SBC__c = 5,
                                                                      Rental_Networks__c = 'Yes');
            insert policy1;  
            
            
            Policy_Information__c pupdate= [select id ,Salesforce_Volume__c,Add_ons_Sum_of_total_input__c from Policy_Information__c where id=:policy1.Id];
            pupdate.Add_ons_Sum_of_total_input__c=100;
            pupdate.Salesforce_Volume__c=100;
            update pupdate;
            
            newMap.put(policy.id,policy);
            oldMap.put(updatedPolicyInfo.id,updatedPolicyInfo);
            DontAllowDuplicatePolicyNumbersHelper.calculateAddOn(newMap,oldMap);
            
            newMap.put(policy.id,policy);
            oldMap.put(policy.id,policy);
            DontAllowDuplicatePolicyNumbersHelper.calculateAddOn(newMap,oldMap);
            
            DontAllowDuplicatePolicyNumbersHelper.complexityLoigicUpdateHandler(newMap,oldMap);
            
            policy.CSP_GSP_or_Extended_Networks__c = null;
            policy.Customer_Sponsored_Service_Center__c = null;
            policy.DHP_Diabetes_Health_Plan__c = null;
            policy.Eligibility__c = null;
            policy.FSA_c__c = null;
            policy.Hospital_Systemss__c = null;
            policy.Life__c	= null;
            policy.Medicare_Plan__c = null;
            policy.ne_Business_Exchange_Transition_Factor__c = null;
            policy.UHG_Owned_Custom_Portal__c = null;
            policy.New_Product_1st_Year_1__c = null;
            //policy.Add_ons_Sum_of_total_input__c = null;
            update policy;
            
            updatedPolicyInfo.CSP_GSP_or_Extended_Networks__c = null;
            updatedPolicyInfo.Customer_Sponsored_Service_Center__c = null;
            updatedPolicyInfo.DHP_Diabetes_Health_Plan__c = null;
            updatedPolicyInfo.Eligibility__c = null;
            updatedPolicyInfo.FSA_c__c = null;
            updatedPolicyInfo.Hospital_Systemss__c = null;
            updatedPolicyInfo.Life__c	= null;
            updatedPolicyInfo.Medicare_Plan__c = null;
            updatedPolicyInfo.ne_Business_Exchange_Transition_Factor__c = null;
            updatedPolicyInfo.UHG_Owned_Custom_Portal__c = null;
            updatedPolicyInfo.New_Product_1st_Year_1__c = null;
            //updatedPolicyInfo.Add_ons_Sum_of_total_input__c = null;
            update updatedPolicyInfo;
            
            newMap.put(policy.id,policy);
            oldMap.put(updatedPolicyInfo.id,updatedPolicyInfo);
            DontAllowDuplicatePolicyNumbersHelper.calculateAddOn(newMap,oldMap);
            
            newMap.put(policy.id,policy);
            oldMap.put(policy.id,policy);
            DontAllowDuplicatePolicyNumbersHelper.calculateAddOn(newMap,oldMap);
            
            DontAllowDuplicatePolicyNumbersHelper.complexityLoigicUpdateHandler(newMap,oldMap);
        	
        	System.assertEquals(1, [SELECT count() FROM Account WHERE Name = 'Test CD Account' ]);
    }
}